---
version: "2.0"
services:
  texttoimage:
    image: cro7/text-2-image-on-akash:0.0.1
    expose:
      - port: 7860
        as: 8051
        to:
          - global: true
profiles:
  compute:
    texttoimage:
      resources:
        cpu:
          units: 6
        memory:
          size: 16Gi
        storage:
          - size: 32Gi
        gpu:
          units: 1
          attributes:
            vendor:
              nvidia:
  placement:
    dcloud:
      pricing:
        texttoimage:
          denom: uakt
          amount: 1000
deployment:
  texttoimage:
    dcloud:
      profile: tts
      count: 1